receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

exporters:
    sapm:
      access_token: ${SPLUNK_ACCESS_TOKEN} 
      endpoint: "https://ingest.us1.signalfx.com/v2/trace" 
    signalfx:
      access_token: ${SPLUNK_ACCESS_TOKEN}
      access_token_passthrough: true
      realm: us1
      timeout: 5s
      max_idle_conns: 80
    debug:
      verbosity: detailed
processors:
    batch:
      timeout: 5s
      send_batch_size: 1024

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    telemetry:
      logs:
        level: debug
    extensions: [pprof, zpages, health_check]
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug,signalfx]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug,sapm]
